python train.py with data_root=./dataset/coco/arrows num_gpus=8 num_nodes=1 task_finetune_vqa per_gpu_batchsize=32 vis_mode="duel" pretrained_vision=True $@
python train.py with data_root=./dataset/coco/arrows num_gpus=8 num_nodes=1 task_finetune_vqa per_gpu_batchsize=32 vis_mode="duel" pretrained_vision=True $@
python train.py with data_root=./dataset/coco/arrows num_gpus=8 num_nodes=1 task_finetune_vqa per_gpu_batchsize=32 vis_mode="duel" pretrained_vision=True $@
python train.py with data_root=./dataset/coco/arrows num_gpus=8 num_nodes=1 task_finetune_vqa per_gpu_batchsize=32 vis_mode="duel" pretrained_vision=True $@
python train.py with data_root=./dataset/coco/arrows num_gpus=8 num_nodes=1 task_finetune_vqa per_gpu_batchsize=32 vis_mode="duel" pretrained_vision=True $@
python train.py with data_root=./dataset/coco/arrows num_gpus=8 num_nodes=1 task_finetune_vqa per_gpu_batchsize=32 vis_mode="duel" pretrained_vision=True $@
python train.py with data_root=./dataset/coco/arrows num_gpus=8 num_nodes=1 task_finetune_vqa per_gpu_batchsize=32 vis_mode="duel" pretrained_vision=True $@
python train.py with data_root=./dataset/coco/arrows num_gpus=8 num_nodes=1 task_finetune_vqa per_gpu_batchsize=32 vis_mode="duel" pretrained_vision=True $@
python train.py with data_root=./dataset/coco/arrows num_gpus=8 num_nodes=1 task_finetune_vqa per_gpu_batchsize=32 vis_mode="duel" pretrained_vision=True $@
python train.py with data_root=./dataset/coco/arrows num_gpus=8 num_nodes=1 task_finetune_vqa per_gpu_batchsize=32 vis_mode="duel" pretrained_vision=True $@